### ISSUE TITLE
Regarding Issue in Setup Process in Linux

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Git-Manager#10]
![error](https://user-images.githubusercontent.com/58029804/90317889-f3771480-df1b-11ea-9931-691dd262320b.png)
while typing git manager after running setup.py and closing current terminal and opening new terminal i get above error ;(

**Comment by gowtham758550** [comment]
Due to absence of request module

**Comment by gowtham758550** [comment]
I will add auto installation for requests module in setup.py

**Comment by Anish-M-code** [comment]
but it works if run main.py directly
