### ISSUE TITLE
Installing github repo fails in Git manager

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Git-Manager#14]
kept internet connection on while trying to clone a github repo seems it no longer works in kali linux and throws error even if github url is valid
![error](https://user-images.githubusercontent.com/58029804/102985386-feb00180-4506-11eb-9666-5b7a84396a37.png)
.
i executed as python3 main.py as this program doesnot support zsh shell yet.

**Comment by gowtham758550** [comment]
now it works, there is problem in importing the urllib module. I fixed that.
