### ISSUE TITLE
Requesting Permission to package git manager in pypi

### ISSUE THREAD

**Issue by evil-user** [gowtham758550/Git-Manager#17]
I would like to be official maintainer of Git manager in pypi , this would make it extremly acessible, this needs lots of work , hence requesting permission.  in terms of security we will enforce maximum security , my version of git manager will aim to be a downstream version of git manager , updates will be only rolled after extensive testing and custom patches will be applied to ensure stability.

**Comment by Anish-M-code** [comment]
you can maintain downstream version but give credits to we developers.

**Comment by gowtham758550** [comment]
> I would like to be official maintainer of Git manager in pypi , this would make it extremly acessible, this needs lots of work , hence requesting permission. in terms of security we will enforce maximum security , my version of git manager will aim to be a downstream version of git manager , updates will be only rolled after extensive testing and custom patches will be applied to ensure stability.

Sure.
