### ISSUE TITLE
Adding a setup file 

### ISSUE THREAD

**Issue by seanmusse** [gowtham758550/Git-Manager#2]
Hey! 
I'm not entirely sure how this feature could be implemented in Windows, we could deal with that later, however I'm currently focusing on Linux; I made a simple script called `.setup.py` which contains the following: 

```python
from pathlib import Path
import os


cwd = os.getcwd()
home = str(Path.home())
alias = "alias git-manager=" + cwd + "/main.py"
bashrc = "echo " + alias + " >> ~/.bashrc"

with open(home + "/.bashrc") as f:
    if alias in f.read():
        print("Already installed")
        exit()
    else:
        os.system(bashrc)
        print("Installed")

```

Essentially I would like to add an alias to `~/.bashrc` so that the user could use this program in whatever directory they wish. However I ran into a bit of a problem: `Permission denied` which is no bueno. After skimming through some Google searches it seems like many other users encounter similar problems while trying to make an alias of a program that involves Git. 

Have you ever dealt with this? Is this even a feature you would like to implement into the program? 

I would also like to take the opportunity to say this program was a very nice idea on your part! I'll definitely be using this in the future :)

Thank you,
Sean

**Comment by gowtham758550** [comment]
Thankyou for your response. I will definitely think of your idea. And close this issue as soon as possible. If you have any other idea to increase the code quality or anything create an issue or pull request. Your are always welcome👍. I take some time to understand what the code actually does bcoz I am just a beginner

**Comment by gowtham758550** [comment]
@Seanmusse now I add the setup file with some changes from your code and it works well for my friend @raagul26. Use the updated Git Manager and give your response if you find any other issue.

**Comment by seanmusse** [comment]
This is awesome, thank you @gowtham758550 ! I've never contributed to a project and am a beginner just like yourself so this was a great experience :) Thank you so much once again 🙌

**Comment by gowtham758550** [comment]
You are always welcome🤗
