### ISSUE TITLE
Git-manager fails to display cloned repos

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Git-Manager#4]
![git2](https://user-images.githubusercontent.com/58029804/87856893-c847d800-c911-11ea-88d6-853c2ff096d7.png)
Git-manager fails to display git repos cloned using this program due to a File Not Found Error.

**Comment by gowtham758550** [comment]
are u delete that git-metadata file 🙄

**Comment by Anish-M-code** [comment]
no honestly i just git cloned git manager and did not delete any file.
