### ISSUE TITLE
Program shows setup successfull even when it fails in linux distros

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Git-Manager#5]
![installerror](https://user-images.githubusercontent.com/58029804/87857014-c3cfef00-c912-11ea-9fa7-f17ec49877ae.png)
Here the program is not installed properly but program says setup successfull.

**Comment by gowtham758550** [comment]
Anish try "git-manager" in New terminal after the setup file is executed

**Comment by gowtham758550** [comment]
After setup file execution you need to try this in new terminal.
