### ISSUE TITLE
Git-manager gives File Not Found error in Linux Distros while installing it with root privileges.

### ISSUE THREAD

**Issue by Anish-M-code** [gowtham758550/Git-Manager#6]
![installboom](https://user-images.githubusercontent.com/58029804/87857035-0a254e00-c913-11ea-9f29-387fe83ea035.png)
Here it seems to use a file git-manager.py which doesnot exist. This should be replaced with main.py

**Comment by gowtham758550** [comment]
The main file is named main.py but in setup file main file is mistakenly as git_manager.py 😂

**Comment by gowtham758550** [comment]
now I change the setup file 👍
